name: Maven Package

on:
  push:
    branches: ['main']

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write  # Needed to publish to GitHub Packages

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'corretto'
        cache: maven
        server-id: github  # Matches the <id> in your distributionManagement
        settings-path: ${{ github.workspace }}

    - name: Deploy with Maven
      run: mvn deploy --settings ${{ github.workspace }}/settings.xml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
