name: Deploy Javadoc to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  javadoc:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'corretto'
        java-version: '21'
        cache: 'maven'

    - name: Build Javadoc
      run: mvn -B javadoc:javadoc

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./target/site/apidocs
        publish_branch: gh-pages
        force_orphan: true