name: Deploy Javadoc to gh-pages branch

on:
  push:
    branches:
      - main

jobs:
  javadoc:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'corretto'
        java-version: '21'
        cache: 'maven'

    - name: Generate Javadoc
      run: mvn -B javadoc:javadoc

    - name: Get project version
      id: get_version
      run: echo "VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> "$GITHUB_OUTPUT"

    - name: Deploy to gh-pages branch
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

        git fetch origin gh-pages
        git checkout gh-pages || git checkout --orphan gh-pages

        rm -rf *
        cp -R target/reports/apidocs/* .

        git add .
        git commit -m "Update Javadoc for version ${{ steps.get_version.outputs.VERSION }}" || echo "No changes to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}